<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setup\Site;
use App\Models\Setup\Zone;
use App\Models\Setup\SiteOffence;

class SiteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		//First make table empty.
		Site::truncate();
		Zone::truncate();
		SiteOffence::truncate();
        //Now insert the data in database
        Site::insert(array(
            array('id' =>1, 'user_id' => '2', 'name' => 'Bolton Council', 'logo' => 'bolton.png', 'slug' => 'bolton', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Bolton', 'geographical_area_id' => 'North', 'geo_color'=> '#000000'),
            array('id' =>2, 'user_id' => '1', 'name' => 'Brentwood Borough Council', 'logo' => 'brentwood.png', 'slug' => 'brentwood', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Brentwood Borough', 'geographical_area_id' => 'South', 'geo_color'=> '#2117e6'), 
            array('id' =>3, 'user_id' => '1', 'name' => 'Bristol City Council', 'logo' => null, 'slug' => 'bristol', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Bristol', 'geographical_area_id' => 'South', 'geo_color'=> '#000000'),
            array('id' =>4, 'user_id' => '2', 'name' => 'Canterbury City Council', 'logo' => 'canterbury.png', 'slug' => 'canterbury', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Canterbury', 'geographical_area_id' => 'South', 'geo_color'=> '#a6195b'),
            array('id' =>5, 'user_id' => '2', 'name' => 'Cyngor Bwrdeistref Sirol Blaenau Gwent County Borough Council', 'logo' => null, 'slug' => 'cyngor-bwrdeistref-sirol-blaenau-gwent', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Ebbw Vale', 'geographical_area_id' => 'South Wales', 'geo_color'=> '#e2bbf0'),
            array('id' =>6, 'user_id' => '2', 'name' => 'Gloucester City Council', 'logo' => null, 'slug' => 'gloucester', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Gloucester City Council', 'geographical_area_id' => 'South', 'geo_color'=> '#000000'),
            array('id' =>7, 'user_id' => '1', 'name' => 'Hammersmith & Fulham Council', 'logo' => null, 'slug' => 'hammersmith', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Hammersmith & Fulham Council', 'geographical_area_id' => 'South', 'geo_color'=> '#e81010'),
            array('id' =>8, 'user_id' => '2', 'name' => 'Harlow District Council', 'logo' => null, 'slug' => 'harlow', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Harlow District Council', 'geographical_area_id' => 'South', 'geo_color'=> '#0eede6'),
            array('id' =>9, 'user_id' => '2', 'name' => 'Knowsley Metropolitan Borough Council', 'logo' => null, 'slug' => 'knowsley', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Knowsley Metropolitan Borough Council', 'geographical_area_id' => 'North', 'geo_color'=> '#bab4b4'),
            array('id' =>10, 'user_id' => '1', 'name' => 'Leeds City Council', 'logo' => null, 'slug' => 'leeds-city', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Leeds City Council', 'geographical_area_id' => 'North', 'geo_color'=> '#12665c'),
            array('id' =>11, 'user_id' => '1', 'name' => 'London Borough of Havering', 'logo' => null, 'slug' => 'london-borough-havering', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'London Borough of Havering', 'geographical_area_id' => 'South', 'geo_color'=> '#8b9bc9'),
            array('id' =>12, 'user_id' => '2', 'name' => 'London Borough of Waltham Forest', 'logo' => null, 'slug' => 'london-borough-waltham', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'London Borough of Waltham Forest', 'geographical_area_id' => 'South', 'geo_color'=> '#000000'),
            array('id' =>13, 'user_id' => '1', 'name' => 'Rother District Council', 'logo' => null, 'slug' => 'rother', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Rother District Council', 'geographical_area_id' => 'South', 'geo_color'=> '#2a7339'),
            array('id' =>14, 'user_id' => '2', 'name' => 'Tonbridge and Malling Borough Council', 'logo' => null, 'slug' => 'tonbridge-malling-borough', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Tonbridge and Malling Borough Council', 'geographical_area_id' => 'South', 'geo_color'=> '#00ff22'),
            array('id' =>15, 'user_id' => '2', 'name' => 'Torbay Council', 'logo' => null, 'slug' => 'torbay', 'region_id' => '1', 'postal_code' => 'HU42 8SY', 'address_line1' => 'Gibson Building, Gibson Drive', 'country' => 'United Kingdom', 'town' => 'Torbay Council', 'geographical_area_id' => 'South', 'geo_color'=> '#000000'),
        ));

        Zone::insert(array(
            array('id' => '1', 'name' => 'Brentwood North', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '2', 'name' => 'Brentwood South', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '3', 'name' => 'Brentwood West', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '4', 'name' => 'Brizes and Doddinghurst', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '5', 'name' => 'Herongate, Ingrave and West Horndon', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '6', 'name' => 'Hutton Central', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '7', 'name' => 'Hutton East', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '8', 'name' => 'Hutton North', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '9', 'name' => 'Hutton South', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '10', 'name' => 'Ingatestone, Fryerning and Mountnessing', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '11', 'name' => 'Pilgrims Hatch', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '12', 'name' => 'Shenfield', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '13', 'name' => 'South Weald', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '14', 'name' => 'Tipps Cross', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '15', 'name' => 'Warley', 'site_id' => '2', 'user_id' => '1'),
            array('id' => '16', 'name' => 'Barton', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '17', 'name' => 'Beltinge', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '18', 'name' => 'Blean Forest', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '19', 'name' => 'Chartham & Stone Street', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '20', 'name' => 'Chestfield', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '21', 'name' => 'Gorrell', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '22', 'name' => 'Greenhill', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '23', 'name' => 'Herne & Broomfield', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '24', 'name' => 'Heron', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '25', 'name' => 'Little Stour & Adisham', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '26', 'name' => 'Nailbourne', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '27', 'name' => 'Northgate', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '28', 'name' => 'Reculver', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '29', 'name' => 'Seasalter', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '30', 'name' => 'St Stephen’s', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '31', 'name' => 'Sturry', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '32', 'name' => 'Swalecliffe', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '33', 'name' => 'Tankerton', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '34', 'name' => 'West Bay', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '35', 'name' => 'Westgate', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '36', 'name' => 'Wincheap', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '37', 'name' => 'DO NOT ISSUE Whitefriars - blacklist', 'site_id' => '4', 'user_id' => '2'),
            array('id' => '38', 'name' => 'Abertyleri/Abertillery', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '39', 'name' => 'Georgetown', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '40', 'name' => 'Llanhiledd/Llanhilleth', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '41', 'name' => 'Sirhywi/Sirhowy', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '42', 'name' => 'Chwe Chloch/Six Bells', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '43', 'name' => 'Tredegar - Canol a Gorllewin/Tredegar - Central an', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '44', 'name' => 'Badminton', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '45', 'name' => 'Beaufort', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '46', 'name' => 'Blaenau/Blaina', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '47', 'name' => 'Brynmawr', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '48', 'name' => 'Cwm', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '49', 'name' => 'Cwmtyleri/Cwmtillery', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '50', 'name' => 'Gogledd Glyn Ebwy/Ebbw Vale North', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '51', 'name' => 'De Glyn Ebwy/Ebbw Vale South', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '52', 'name' => 'Nantyglo', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '53', 'name' => 'Rasau/Rassau', 'site_id' => '5', 'user_id' => '1'),
            array('id' => '54', 'name' => 'Borough of Hammersmith & Fulham', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '55', 'name' => 'Addison', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '56', 'name' => 'Askew', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '57', 'name' => 'Avonmore and Brook Green', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '58', 'name' => 'Brook Green', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '59', 'name' => 'College Park and Old Oak', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '60', 'name' => 'Fulham Broadway', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '61', 'name' => 'Fulham Reach', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '62', 'name' => 'Hammersmith Broadway', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '63', 'name' => 'Munster', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '64', 'name' => 'North End', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '65', 'name' => 'Old Oak', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '66', 'name' => 'Palace Riverside', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '67', 'name' => 'Parsons Green and Walham', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '68', 'name' => 'Ravenscourt Park', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '69', 'name' => 'Sands End', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '70', 'name' => 'Town', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '71', 'name' => 'Shepherds Bush Green', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '72', 'name' => 'Wormholt and White City', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '73', 'name' => 'Walham', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '74', 'name' => 'White City', 'site_id' => '7', 'user_id' => '2'),
            array('id' => '75', 'name' => 'Little Parndon and Hare Street', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '76', 'name' => 'Netteswell', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '77', 'name' => 'Mark Hall', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '78', 'name' => 'Old Harlow', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '79', 'name' => 'Great Parndon', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '80', 'name' => 'Toddbrook', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '81', 'name' => 'Bush Fair', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '82', 'name' => 'Church Langley', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '83', 'name' => 'Harlow Common', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '84', 'name' => 'Staple Tye', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '85', 'name' => 'Sumners and Kingsmoor', 'site_id' => '8', 'user_id' => '1'),
            array('id' => '86', 'name' => 'Cherryfield', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '87', 'name' => 'Halewood North', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '88', 'name' => 'Halewood South', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '89', 'name' => 'Northwood', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '90', 'name' => 'Page Moss', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '91', 'name' => 'Prescot North', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '92', 'name' => 'Prescot South', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '93', 'name' => 'Roby', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '94', 'name' => 'Shevington', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '95', 'name' => 'St Gabriels', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '96', 'name' => 'St Michaels', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '97', 'name' => 'Stockbridge', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '98', 'name' => 'Swanside', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '99', 'name' => 'Whiston and Cronton', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '100', 'name' => 'Whitefield', 'site_id' => '9', 'user_id' => '2'),
            array('id' => '101', 'name' => 'Garforth and Swillington', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '102', 'name' => 'Harewood', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '103', 'name' => 'Kippax and Methley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '104', 'name' => 'Rothwell', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '105', 'name' => 'Wetherby', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '106', 'name' => 'Beeston and Holbeck', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '107', 'name' => 'Burmantofts and Richmond Hill', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '108', 'name' => 'Little London and Woodhouse', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '109', 'name' => 'Hunslet and Riverside', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '110', 'name' => 'Middleton Park', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '111', 'name' => 'Cross Gates and Whinmoor', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '112', 'name' => 'Gipton and Harehills', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '113', 'name' => 'Killingbeck and Seacroft', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '114', 'name' => 'Temple Newsam', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '115', 'name' => 'Alwoodley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '116', 'name' => 'Chapel Allerton', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '117', 'name' => 'Moortown', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '118', 'name' => 'Roundhay', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '119', 'name' => 'Adel and Wharfedale', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '120', 'name' => 'Headingley and Hyde Park', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '121', 'name' => 'Otley and Yeadon', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '122', 'name' => 'Weetwood', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '123', 'name' => 'Armley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '124', 'name' => 'Bramley and Stanningley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '125', 'name' => 'Farnley and Wortley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '126', 'name' => 'Kirkstall', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '127', 'name' => 'Ardsley and Robin Hood', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '128', 'name' => 'Morley North', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '129', 'name' => 'Morley South', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '130', 'name' => 'Calverley and Farsley', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '131', 'name' => 'Guiseley and Rawdon', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '132', 'name' => 'Horsforth', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '133', 'name' => 'Pudsey', 'site_id' => '10', 'user_id' => '1'),
            array('id' => '134', 'name' => 'Havering Park', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '135', 'name' => 'Gooshays', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '136', 'name' => 'Mawneys', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '137', 'name' => 'Pettits', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '138', 'name' => 'Heaton', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '139', 'name' => 'Harold Wood', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '140', 'name' => 'Brooklands', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '141', 'name' => 'Romford Town', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '142', 'name' => 'Squirrels Heath', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '143', 'name' => 'Emerson Park', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '144', 'name' => 'Cranham', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '145', 'name' => 'Hylands', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '146', 'name' => 'St Andrews', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '147', 'name' => 'Elm Park', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '148', 'name' => 'Hacton', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '149', 'name' => 'Upminster', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '150', 'name' => 'South Hornchurch', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '151', 'name' => 'Rainham & Wennington', 'site_id' => '11', 'user_id' => '2'),
            array('id' => '152', 'name' => 'Bexhill Central', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '153', 'name' => 'Bexhill Kewhurst', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '154', 'name' => 'Bexhill Pebsham & St Michaels', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '155', 'name' => 'Bexhill Sidley', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '156', 'name' => 'Bexhill St Stephens', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '157', 'name' => 'Burwash & The Weald', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '158', 'name' => 'Eastern Rother', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '159', 'name' => 'North Battle, Netherfield & Whatlington', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '160', 'name' => 'Robertsbridge', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '161', 'name' => 'Sedlescombe & Westfield', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '162', 'name' => 'Southern Rother', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '163', 'name' => 'Bexhill Collington', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '164', 'name' => 'Bexhill Old Town & Worsham', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '165', 'name' => 'Bexhill Sackville', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '166', 'name' => 'Bexhill St Marks', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '167', 'name' => 'Brede & Udimore', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '168', 'name' => 'Catsfield & Crowhurst', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '169', 'name' => 'Hurst Green & Ticehurst', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '170', 'name' => 'Northern Rother', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '171', 'name' => 'Rye & Winchelsea', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '172', 'name' => 'South Battle & Telham', 'site_id' => '13', 'user_id' => '1'),
            array('id' => '173', 'name' => 'Aylesford North and Walderslade', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '174', 'name' => 'Aylesford South', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '175', 'name' => 'Borough Green and Long Mill', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '176', 'name' => 'Burham and Wouldham', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '177', 'name' => 'Cage Green', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '178', 'name' => 'Castle', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '179', 'name' => 'Ditton', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '180', 'name' => 'Downs and Mereworth', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '181', 'name' => 'East Malling', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '182', 'name' => 'Hadlow and East Peckham', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '183', 'name' => 'Higham', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '184', 'name' => 'Hildenborough', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '185', 'name' => 'Judd', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '186', 'name' => 'Kings Hill', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '187', 'name' => 'Larkfield North', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '188', 'name' => 'Larkfield South', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '189', 'name' => 'Medway', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '190', 'name' => 'Snodland East and Ham Hill', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '191', 'name' => 'Snodland West and Holborough Lakes', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '192', 'name' => 'Trench', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '193', 'name' => 'Vauxhall', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '194', 'name' => 'Wateringbury', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '195', 'name' => 'West Malling and Leybourne', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '196', 'name' => 'Wrotham, Ightham and Stansted', 'site_id' => '14', 'user_id' => '2'),
            array('id' => '197', 'name' => 'Barton with Watcombe', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '198', 'name' => 'Churston with Galmpton', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '199', 'name' => 'Clifton with Maidenway', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '200', 'name' => 'Cockington with Chelston', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '201', 'name' => 'Collaton St Mary', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '202', 'name' => 'Ellacombe', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '203', 'name' => 'Furzeham with Summercomb', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '204', 'name' => 'Goodrington with Roselands', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '205', 'name' => 'Kings Ash', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '206', 'name' => 'Preston', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '207', 'name' => 'Roundham with Hyde', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '208', 'name' => 'Shiphay', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '209', 'name' => 'St Marychurch', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '210', 'name' => 'St Peters with St Marys', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '211', 'name' => 'Tormohun', 'site_id' => '15', 'user_id' => '1'),
            array('id' => '212', 'name' => 'Wellswood', 'site_id' => '15', 'user_id' => '1'),
        ));

        for($i = 1; $i < 16; $i++)
        {
            SiteOffence::insert([
                [
                    'site_id' => $i,
                    'offence_id' => 1,
                    'offence_group_id' => 1
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 2,
                    'offence_group_id' => 1
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 3,
                    'offence_group_id' => 17

                ],
                [
                    'site_id' => $i,
                    'offence_id' => 4,
                    'offence_group_id' => 3
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 5,
                    'offence_group_id' => 4
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 6,
                    'offence_group_id' => 6
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 7,
                    'offence_group_id' => 1
                ],
                [
                    'site_id' => $i,
                    'offence_id' => 8,
                    'offence_group_id' => 1
                ],
            ]);
        }

    }
}
